server:
  port: 8080
  forward-headers-strategy: native
  ssl:
    key-store: keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: titlecounter
spring:
  application:
    name: team-selection
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://team-selection-postgres:5432/team-selection
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    schemas: public
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jpa:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
frontend:
  url: https://titlecounter.ru:5173
  login:
    url: https://titlecounter.ru:5173/login
cors:
  allowed-origins: https://titlecounter.ru:8080

logging:
  level:
    org.springframework.security: DEBUG