server:
  port: 8080
# TODO enable ssl
#  forward-headers-strategy: native
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/ts.p12
#    key-store-password:
#    key-alias: ts
#    enabled: true


spring:
  application:
    name: team-selection
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    hikari:
      maximum-pool-size: 50
      jdbc-url: jdbc:postgresql://localhost:5432/team-selection
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver
    url: http://localhost:5432
  flyway:
    user: postgres
    password: 1234
    schemas: public
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jpa:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# TODO learn how to enable this
  cloud:
    azure:
      active-directory:
        enabled: false
        profile:
          tenant-id:
        credential:
          client-id:
          client-secret:
        redirect-uri-template: https://147.45.108.155:8080/login/oauth2/code/
#        redirect-uri-template: https://localhost:8080/login/oauth2/code/
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
#            scopes: https://graph.microsoft.com/User.Read
#            scopes: https://graph.microsoft.com/Analytics.Read, https://graph.microsoft.com/User.Read
#        b2c:
#          user-name-attribute-name: email




logging:
  level:
    org.springframework.security: DEBUG