server:
  port: 8080
  forward-headers-strategy: native
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/ts.p12
#    key-store-password:
#    key-alias: ts
#    enabled: true
spring:
  application:
    name: team-selection
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/team-selection
    username: postgres
    password: 1234
  flyway:
    user: postgres
    password: 1234
    schemas: public
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jpa:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
        registration:
          github:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
          azure:
            provider: azure
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
  cloud:
    azure:
      active-directory:
        enabled: false
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        redirect-uri-template: http://localhost:8080/login/oauth2/code/azure
        application-type: WEB_APPLICATION
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
              - email
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

app:
  scheduler:
    enabled: true
    studentTrack: "0 0 0 * * ?"

cors:
  allowed-origins: http://localhost:8080

frontend:
  url: http://localhost:5173
  login:
    url: http://localhost:5173/login

# /oauth2/authorization/github
logging:
  level:
    org.springframework.security: TRACE