INSERT INTO public.technologies VALUES (1, 'C++');
INSERT INTO public.technologies VALUES (2, 'C#');
INSERT INTO public.technologies VALUES (3, 'Python');
INSERT INTO public.technologies VALUES (4, 'Java');
INSERT INTO public.technologies VALUES (5, 'Frontend');
INSERT INTO public.technologies VALUES (6, 'Backend');
INSERT INTO public.technologies VALUES (7, 'Ruby');
INSERT INTO public.technologies VALUES (8, 'Kotlin');
INSERT INTO public.technologies VALUES (32, 'PostgreSQL');
INSERT INTO public.technologies VALUES (33, 'Docker');
INSERT INTO public.technologies VALUES (34, 'MongoDB');
INSERT INTO public.technologies VALUES (35, 'Flutter');
INSERT INTO public.technologies VALUES (36, '.NET');
INSERT INTO public.technologies VALUES (37, 'Entity Framework');
INSERT INTO public.technologies VALUES (38, 'Redux');
INSERT INTO public.technologies VALUES (39, 'Vue.js');
INSERT INTO public.technologies VALUES (40, 'Unity');
INSERT INTO public.technologies VALUES (41, 'Unreal Engine');
INSERT INTO public.technologies VALUES (42, 'PHP');
INSERT INTO public.technologies VALUES (43, 'Symfony');
INSERT INTO public.technologies VALUES (44, 'Laravel');
INSERT INTO public.technologies VALUES (45, 'Django');
INSERT INTO public.technologies VALUES (46, 'Flask');
INSERT INTO public.technologies VALUES (47, 'Node.js');
INSERT INTO public.technologies VALUES (48, 'AngularJS');
INSERT INTO public.technologies VALUES (49, 'React Native');
INSERT INTO public.technologies VALUES (50, 'Godot');
INSERT INTO public.technologies VALUES (51, 'RenPy');
INSERT INTO public.technologies VALUES (9, 'Dart');
INSERT INTO public.technologies VALUES (10, 'Swift');
INSERT INTO public.technologies VALUES (11, 'Go');
INSERT INTO public.technologies VALUES (12, 'JavaScript');
INSERT INTO public.technologies VALUES (13, 'TypeScript');
INSERT INTO public.technologies VALUES (14, 'HTML');
INSERT INTO public.technologies VALUES (15, 'CSS');
INSERT INTO public.technologies VALUES (16, 'SQL');
INSERT INTO public.technologies VALUES (17, 'GameDev');
INSERT INTO public.technologies VALUES (18, 'ML');
INSERT INTO public.technologies VALUES (19, 'DevOps');
INSERT INTO public.technologies VALUES (20, 'Analytics');
INSERT INTO public.technologies VALUES (21, 'Android');
INSERT INTO public.technologies VALUES (22, 'iOS');
INSERT INTO public.technologies VALUES (23, 'CrossPlatform');
INSERT INTO public.technologies VALUES (24, 'Mobile');
INSERT INTO public.technologies VALUES (25, 'Desktop');
INSERT INTO public.technologies VALUES (26, 'Web');
INSERT INTO public.technologies VALUES (27, 'React');
INSERT INTO public.technologies VALUES (28, 'Spring');
INSERT INTO public.technologies VALUES (29, 'Ruby On Rails');
INSERT INTO public.technologies VALUES (30, 'Tailwind CSS');
INSERT INTO public.technologies VALUES (31, 'MySQL');

SELECT pg_catalog.setval('technologies_id_seq', 51, true);
