CREATE TABLE project_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(32),
   CONSTRAINT pk_project_types PRIMARY KEY (id)
);

ALTER TABLE teams ADD project_type_id BIGINT;

ALTER TABLE project_types ADD CONSTRAINT uc_project_types_name UNIQUE (name);

ALTER TABLE teams ADD CONSTRAINT FK_TEAMS_ON_PROJECTTYPE FOREIGN KEY (project_type_id) REFERENCES project_types (id);

ALTER TABLE teams DROP COLUMN project_type;

