name: Build and test application

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/build_and_test.yml'


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build
    environment: Deploy
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: maven build
        working-directory: .
        run: mvn -am package

      - name: Run tests
        working-directory: .
        run: mvn -am verify
